name: example
description: Example app for flutter_minimal_design
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_minimal_design:
    path: ../
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

